// Code generated by astisrt using internal/cmd/generate/static_consts. DO NOT EDIT.
#include <srt/srt.h>

static const int32_t SRTGROUP_MASK_;
static const int SRT_LIVE_DEF_PLSIZE_;
static const int SRT_LIVE_MAX_PLSIZE_;
static const int SRT_LIVE_DEF_LATENCY_MS_;
static const SRTSOCKET SRT_INVALID_SOCK_;
static const int SRT_ERROR_;
static const int32_t SRT_SEQNO_NONE_;
static const int32_t SRT_MSGNO_NONE_;
static const int32_t SRT_MSGNO_CONTROL_;
static const int SRT_MSGTTL_INF_;
static const uint32_t SRT_GFLAG_SYNCONMSG_;
