// Code generated by astisrt using internal/cmd/wrap. DO NOT EDIT.
#include <srt/srt.h>
#include "callbacks.h"

int astisrt_getsockflag(SRTSOCKET u, SRT_SOCKOPT opt, void* optval, int* optlen, int *srtErrno, int *sysErrno);
int astisrt_setsockflag(SRTSOCKET u, SRT_SOCKOPT opt, const void* optval, int optlen, int *srtErrno, int *sysErrno);
int astisrt_startup(int *srtErrno, int *sysErrno);
int astisrt_cleanup(int *srtErrno, int *sysErrno);
SRTSOCKET astisrt_create_socket(int *srtErrno, int *sysErrno);
int astisrt_close(SRTSOCKET u, int *srtErrno, int *sysErrno);
int astisrt_bind(SRTSOCKET u, const struct sockaddr* name, int namelen, int *srtErrno, int *sysErrno);
int astisrt_listen(SRTSOCKET u, int backlog, int *srtErrno, int *sysErrno);
int astisrt_connect(SRTSOCKET u, const struct sockaddr* name, int namelen, int *srtErrno, int *sysErrno, int *rejectReason);
SRTSOCKET astisrt_accept(SRTSOCKET u, struct sockaddr* addr, int* addrlen, int *srtErrno, int *sysErrno);
int astisrt_listen_callback(SRTSOCKET lsn, void* opaque, int *srtErrno, int *sysErrno);
int astisrt_connect_callback(SRTSOCKET clr, void* opaque, int *srtErrno, int *sysErrno);
int astisrt_setrejectreason(SRTSOCKET sock, int value, int *srtErrno, int *sysErrno);
int astisrt_bistats(SRTSOCKET u, SRT_TRACEBSTATS* perf, int clear, int instantaneous, int *srtErrno, int *sysErrno);
int astisrt_recvmsg2(SRTSOCKET u, char* buf, int len, SRT_MSGCTRL* mctrl, int *srtErrno, int *sysErrno);
int astisrt_sendmsg2(SRTSOCKET u, char* buf, int len, SRT_MSGCTRL* mctrl, int *srtErrno, int *sysErrno);