// Code generated by astisrt using internal/cmd/wrap. DO NOT EDIT.
#include <srt/srt.h>
#include "callbacks.h"

int astisrt_getsockflag(SRTSOCKET u, SRT_SOCKOPT opt, void* optval, int* optlen, int *srtErrno, int *sysErrno) {
	int ret = srt_getsockflag(u, opt, optval, optlen);
	if (ret == SRT_ERROR) {
		*srtErrno = srt_getlasterror(sysErrno);
		srt_clearlasterror();
	}
	return ret;
}

int astisrt_setsockflag(SRTSOCKET u, SRT_SOCKOPT opt, const void* optval, int optlen, int *srtErrno, int *sysErrno) {
	int ret = srt_setsockflag(u, opt, optval, optlen);
	if (ret == SRT_ERROR) {
		*srtErrno = srt_getlasterror(sysErrno);
		srt_clearlasterror();
	}
	return ret;
}

int astisrt_startup(int *srtErrno, int *sysErrno) {
	int ret = srt_startup();
	if (ret == SRT_ERROR) {
		*srtErrno = srt_getlasterror(sysErrno);
		srt_clearlasterror();
	}
	return ret;
}

int astisrt_cleanup(int *srtErrno, int *sysErrno) {
	int ret = srt_cleanup();
	if (ret == SRT_ERROR) {
		*srtErrno = srt_getlasterror(sysErrno);
		srt_clearlasterror();
	}
	return ret;
}

SRTSOCKET astisrt_create_socket(int *srtErrno, int *sysErrno) {
	SRTSOCKET ret = srt_create_socket();
	if (ret == SRT_INVALID_SOCK) {
		*srtErrno = srt_getlasterror(sysErrno);
		srt_clearlasterror();
	}
	return ret;
}

int astisrt_close(SRTSOCKET u, int *srtErrno, int *sysErrno) {
	int ret = srt_close(u);
	if (ret == SRT_ERROR) {
		*srtErrno = srt_getlasterror(sysErrno);
		srt_clearlasterror();
	}
	return ret;
}

int astisrt_bind(SRTSOCKET u, const struct sockaddr* name, int namelen, int *srtErrno, int *sysErrno) {
	int ret = srt_bind(u, name, namelen);
	if (ret == SRT_ERROR) {
		*srtErrno = srt_getlasterror(sysErrno);
		srt_clearlasterror();
	}
	return ret;
}

int astisrt_listen(SRTSOCKET u, int backlog, int *srtErrno, int *sysErrno) {
	int ret = srt_listen(u, backlog);
	if (ret == SRT_ERROR) {
		*srtErrno = srt_getlasterror(sysErrno);
		srt_clearlasterror();
	}
	return ret;
}

int astisrt_connect(SRTSOCKET u, const struct sockaddr* name, int namelen, int *srtErrno, int *sysErrno, int *rejectReason) {
	int ret = srt_connect(u, name, namelen);
	if (ret == SRT_ERROR) {
		*srtErrno = srt_getlasterror(sysErrno);
		srt_clearlasterror();
		if (*srtErrno == SRT_ECONNREJ) {
			*rejectReason = srt_getrejectreason(u);
		}
	}
	return ret;
}

SRTSOCKET astisrt_accept(SRTSOCKET u, struct sockaddr* addr, int* addrlen, int *srtErrno, int *sysErrno) {
	SRTSOCKET ret = srt_accept(u, addr, addrlen);
	if (ret == SRT_INVALID_SOCK) {
		*srtErrno = srt_getlasterror(sysErrno);
		srt_clearlasterror();
	}
	return ret;
}

int astisrt_listen_callback(SRTSOCKET lsn, void* opaque, int *srtErrno, int *sysErrno) {
	int ret = srt_listen_callback(lsn, astisrt_listen_callback_fn, opaque);
	if (ret == SRT_ERROR) {
		*srtErrno = srt_getlasterror(sysErrno);
		srt_clearlasterror();
	}
	return ret;
}

int astisrt_connect_callback(SRTSOCKET clr, void* opaque, int *srtErrno, int *sysErrno) {
	int ret = srt_connect_callback(clr, astisrt_connect_callback_fn, opaque);
	if (ret == SRT_ERROR) {
		*srtErrno = srt_getlasterror(sysErrno);
		srt_clearlasterror();
	}
	return ret;
}

int astisrt_setrejectreason(SRTSOCKET sock, int value, int *srtErrno, int *sysErrno) {
	int ret = srt_setrejectreason(sock, value);
	if (ret == SRT_ERROR) {
		*srtErrno = srt_getlasterror(sysErrno);
		srt_clearlasterror();
	}
	return ret;
}

int astisrt_bistats(SRTSOCKET u, SRT_TRACEBSTATS* perf, int clear, int instantaneous, int *srtErrno, int *sysErrno) {
	int ret = srt_bistats(u, perf, clear, instantaneous);
	if (ret == SRT_ERROR) {
		*srtErrno = srt_getlasterror(sysErrno);
		srt_clearlasterror();
	}
	return ret;
}

int astisrt_recvmsg2(SRTSOCKET u, char* buf, int len, SRT_MSGCTRL* mctrl, int *srtErrno, int *sysErrno) {
	int ret = srt_recvmsg2(u, buf, len, mctrl);
	if (ret == SRT_ERROR) {
		*srtErrno = srt_getlasterror(sysErrno);
		srt_clearlasterror();
	}
	return ret;
}

int astisrt_sendmsg2(SRTSOCKET u, char* buf, int len, SRT_MSGCTRL* mctrl, int *srtErrno, int *sysErrno) {
	int ret = srt_sendmsg2(u, buf, len, mctrl);
	if (ret == SRT_ERROR) {
		*srtErrno = srt_getlasterror(sysErrno);
		srt_clearlasterror();
	}
	return ret;
}
